version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "event-based-iac-provisioning"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-py2zkke7qtc"
s3_prefix = "event-based-iac-provisioning"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
