AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Get:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Handler: Account.Functions::Account.Functions.Functions::Get
      Runtime: dotnet6
      CodeUri: ''
      MemorySize: 256
      Timeout: 30
      Role:
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: "/"
            Method: GET

Outputs:
  ApiURL:
    Description: API endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
